### ISSUE TITLE
OS X binary not available 

### ISSUE THREAD

**Issue by YonghuiDong** [osenan/cliqueMS#1]
Hi Oriol,

I am unable to install cliqueMS in OS X system. Could you make OS X binary available as well?

Thanks.

Dong

**Comment by osenan** [comment]
Dear @YonghuiDong,

There is a binary file on the folder `MacOS` with `cliqueMS` version 0.3.0, here on the Github repository. Moreover we are trying to upload `cliqueMS` to the Bioconductor repository, so it would be more available to all OS X systems.
